import type { Metadata } from 'next'
import './reset.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import { theme } from '@/libs/mui/theme'
import { Header, Sidebar } from '@/components'
import { Box } from '@mui/material'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja'>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Header />
            <Box sx={{ display: 'flex', paddingTop: 7 }}>
              <Sidebar />
              <Box
                component='main'
                sx={{ width: '100%', margin: 6, marginLeft: 36 }}
              >
                {children}
              </Box>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
