export { default as SlideList } from './admin/SlideList'
export { default as SlideEditor } from './admin/SlideEditor'
export { default as SlideEditorList } from './admin/SlideEditorList'
export { default as ImageUploader } from './admin/ImageUploader'
export { default as MultilingualSettingModal } from './admin/MultilingualSettingModal'
export { default as SlideEditFooter } from './admin/SlideEditFooter'
